import type { LoginRecord } from "./types";

export const loginRecords: LoginRecord[] = [
  {
    id: "rec-1",
    user: "rohan@example.com",
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    location: "Mumbai, India",
    platform: { os: "Windows", browser: "Chrome" },
    avatarUrl: "https://i.pravatar.cc/150?u=rec-1",
    paymentMethod: "GPay",
  },
  {
    id: "rec-2",
    user: "priya@example.com",
    timestamp: new Date(Date.now() - 1000 * 60 * 23).toISOString(),
    location: "Bengaluru, India",
    platform: { os: "macOS", browser: "Safari" },
    avatarUrl: "https://i.pravatar.cc/150?u=rec-2",
    paymentMethod: "Credit Card",
  },
  {
    id: "rec-3",
    user: "amit@example.com",
    timestamp: new Date(Date.now() - 1000 * 60 * 58).toISOString(),
    location: "Delhi, India",
    platform: { os: "Windows", browser: "Firefox" },
    avatarUrl: "https://i.pravatar.cc/150?u=rec-3",
    paymentMethod: "PhonePe",
  },
  {
    id: "rec-4",
    user: "sneha@example.com",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    location: "Chennai, India",
    platform: { os: "Ubuntu", browser: "Chrome" },
    avatarUrl: "https://i.pravatar.cc/150?u=rec-4",
    paymentMethod: "Net Banking",
  },
  {
    id: "rec-5",
    user: "vikram@example.com",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    location: "Hyderabad, India",
    platform: { os: "Windows", browser: "Edge" },
    avatarUrl: "https://i.pravatar.cc/150?u=rec-5",
    paymentMethod: "Credit Card",
  },
  {
    id: "rec-6",
    user: "anjali@example.com",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    location: "Pune, India",
    platform: { os: "macOS", browser: "Chrome" },
    avatarUrl: "https://i.pravatar.cc/150?u=rec-6",
    paymentMethod: "Paytm",
  },
  {
    id: "rec-7",
    user: "karan@example.com",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 15).toISOString(),
    location: "Kolkata, India",
    platform: { os: "Windows", browser: "Chrome" },
    avatarUrl: "https://i.pravatar.cc/150?u=rec-7",
    paymentMethod: "Debit Card",
  },
  {
    id: "rec-8",
    user: "meera@example.com",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
    location: "Jaipur, India",
    platform: { os: "Android", browser: "Chrome Mobile" },
    avatarUrl: "https://i.pravatar.cc/150?u=rec-8",
    paymentMethod: "PhonePe",
  },
    {
    id: "rec-9",
    user: "admin",
    timestamp: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
    location: "Remote",
    platform: { os: "Linux", browser: "Chrome" },
    paymentMethod: "N/A",
  },
    {
    id: "rec-10",
    user: "customer10@example.com",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
    location: "Ahmedabad, India",
    platform: { os: "iOS", browser: "Safari Mobile" },
    avatarUrl: "https://i.pravatar.cc/150?u=rec-10",
    paymentMethod: "GPay",
  },
];
